name: flutter_samples
description: Flutter samples contains several examples which will be useful in future development.

dependencies:
  flutter:
    sdk: flutter

  location: ^1.3.4
  http: ^0.11.3+16
  image_picker: ^0.4.6

  cupertino_icons: ^0.1.2


flutter:
  uses-material-design: true
